# Generated by Django 4.2 on 2025-04-04 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('nome', models.CharField(max_length=200)),
                ('especialidade', models.CharField(choices=[('CAR', 'Cardiologista'), ('ORT', 'Ortopedista')], max_length=100)),
                ('crm', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=200)),
                ('data', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico')),
            ],
        ),
    ]
