# Generated by Django 4.2 on 2025-04-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('agendado', 'agendado'), ('realizado', 'realizado'), ('cancelado', 'cancelado')], max_length=100),
        ),
    ]
